# Análise exploratória dos dados
_EDA - Exploratory Data Analysis_

---

## Sumário

1. **Importação de bibliotecas**
2. **Carregamento da base**
3. **Análise do dataframe**
   - 3.1. Volumetria
   - 3.2. Tipagem, Nulos e Cardinalidade
   - 3.3. Duplicidade
   - 3.4. Medidas Estatísticas
   - 3.5. Boxplot e Outliers das Variáveis Numéricas
   - 3.6. Distribuição das Variáveis Numéricas
   - 3.7. Análise da Distribuição das Variáveis Numéricas
4. **Análise exploratória dos dados**
   - 4.1. Análise demográfica
      - 4.1.1. Qual a distribuição da idade dos clientes?
      - 4.1.2. O gênero dos clientes está balanceado?
      - 4.1.3. Há diferença de idade média entre gêneros?
      - 4.1.4. O valor médio de compra difere entre gêneros?
      - 4.1.5. Idade influencia o valor do carro comprado?
      - 4.1.6. Existe uma faixa etária que tende a gastar mais?
   - 4.2. Análise financeira
      - 4.2.1. Como é a distribuição da renda anual?
      - 4.2.2. Qual a relação de entre renda e valor de compra?
      - 4.2.3. Clientes com mais dívida compram carros mais caros?
      - 4.2.4. O patrimônio líquido tem relação com o valor de compra?
      - 4.2.5. Renda, dívida e patrimônio são correlacionados entre si?
5. **Insights e recomendações**

<br>

---

<br>

## 1. Importação de bibliotecas

In [1]:
# Importação de bibliotecas e definições de parâmetros

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [2]:
# Configurações para exibição de dados no Jupyter Notebook

# Configurar opção para exibir todas as linhas do Dataframe
pd.set_option('display.max_rows', None)

# Configurar para exibir o conteúdo completo das colunas
pd.set_option('display.max_colwidth', None)

# Configurar a supressão de mensagens de aviso durante a execução
warnings.filterwarnings('ignore')

# Configurar estilo dos gráficos do seaborn
sns.set_style('whitegrid')

## 2. Carregamento da base

In [3]:
# Criando um dataframe a partir do arquivo CSV
df = pd.read_csv('../data/raw/Churn_Modelling.csv', sep=',', encoding='utf-8')
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

## 3. Análise do dataframe

### 3.1. Volumetria

In [4]:
# Exibindo a quantidade de linhas e coluna do dataframe

print(f'Quantidade de linhas (registros):  {df.shape[0]}')
print(f'Quantidade de colunas (variáveis): {df.shape[1]}')

Quantidade de linhas (registros):  10000
Quantidade de colunas (variáveis): 14

### 3.2. Tipagem, Nulos e Cardinalidade

In [23]:
def generate_metada(dataframe):
    '''
    Gera um dataframe contendo metadados das colunas do dataframe fornecido.

    :param dataframe: Dataframe
        DataFrame para o qual os metadados serão gerados.
    :return: DataFrame
        DataFrame contendo os metadados.
    '''

    # Calculando as métricas
    metadata = pd.DataFrame({
        'Variável': dataframe.columns,
        'Tipo de Dado': dataframe.dtypes.values,
        'Quantidade de Valores Únicos': dataframe.nunique().values,
        'Quantidade de Valores Nulos': dataframe.isnull().sum().values,
        'Porcentagem de Valores Nulos': (dataframe.isnull().mean() * 100).values
    })

    return metadata

In [24]:
# Exibindo os metadados do dataframe

generate_metada(df)

,Variável,Tipo de Dado,Quantidade de Valores Únicos,Quantidade de Valores Nulos,Porcentagem de Valores Nulos
0,RowNumber,int64,10000,0,0.0
1,CustomerId,int64,10000,0,0.0
2,Surname,str,2932,0,0.0
3,CreditScore,int64,460,0,0.0
4,Geography,str,3,0,0.0
5,Gender,str,2,0,0.0
6,Age,int64,70,0,0.0
7,Tenure,int64,11,0,0.0
8,Balance,float64,6382,0,0.0
9,NumOfProducts,int64,4,0,0.0
10,HasCrCard,int64,2,0,0.0
11,IsActiveMember,int64,2,0,0.0
12,EstimatedSalary,float64,9999,0,0.0
13,Exited,int64,2,0,0.0